#-------------------------------
# Site Settings

title: Eugene Rodolphe
logo: # You can add own logo. For example '/images/logo.png'.
description: Eugene – Portfolio pour la soutenance master IN'TECH

menu__settings:
  menu__items:
    - title: 'Accueil'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Compétences'
      submenu:
      - url: '/blog/'
        title: 'Téchniques'
      - url: '/skillshumans/'
        title: 'Humaines'
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/certifications'
        title: 'Certifications'

# Call to action button
cta__button__text: Prenez Contact

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Eugene Rodolphe MAZAMDA TANGUEU
  title: Eugene MAZAMDA 
  bio: Architecte Junior Cloud & DevOps basé en France, je met en oeuvres des architecture cloud, conception des plateformes web, automatisation et industrialisation des services clouds. Quand je ne travaille pas, je suis probablement en train de cuisiner ou de voyager quelque part dans le monde. 
  image: '/images/me.jpg'
  avatar: '/images/avatar.jpg'
  button__text: Mes réalisations


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Dernières <span class="text-span">Réalisations</span> # Add a 'text-span' class to highlight text.
  projects__description: Je vous presente les meilleures réalisations web , cloud et DevOps construits entièrement avec passion, simplicité et créativité !


#-------------------------------
# Testimonials Section

testimonial__title: Mon <span class="text-span">Equipe</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Alexandre CHHAN"
    image: "/images/client-1.jpg"
    designation : "Traveler"
    content : "Mettre le témoinages Alexandre ici et la photo si possible."

  - name: "Guillaume F"
    image: "/images/client-2.jpg"
    designation : "Designer"
    content : "Mettre le témoinages de Guillaume ici et la photo si possible !!!."

  - name: "Noël"
    image: "/images/client-3.jpg"
    designation : "CEO, Founder"
    content : "Mettre le témoinages de Noël ici et la photo si possible !!!."

  - name: "Salim LE BIHAN"
    image: "/images/client-4.jpg"
    designation : "Full stack developer"
    content : "Mettre le témoinages de Salim et la photo si possible  ici !!!."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Mes <span class="text-span">Compétences </span> # Add a 'text-span' class to highlight text.
  blog__description:

#-----------------------
# Skills Human
skills__settings:
  skills__title: Mes <span class="text-span">Compétences Humaine</span>
  skills__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: mazamdatangueu@et.intechinfo.fr # Add your email for contact form
  contact__title: <span class="text-span">Prenez</span> Contact # Add a title to your form
  contact__description: Formulaire de contact. # Add a description to your form

# NOTE


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: eugenestudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/eug%C3%A8ne-rodolphe-mazamda-tangueu-82612b151/"}
- {icon: "ion-logo-github", link: "https://github.com/eugenemazamda"}
- {icon: "ion-logo-gitlab", link: "https://gitlab.com/rodolphemazamda"}
- {icon: "ion-logo-facebook", link: "https://codepen.io"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
- {icon: "ion-logo-youtube", link: "https://youtube.com"}