#-------------------------------
# Site Settings

title: Mazamda Tangueu
logo: # You can add own logo. For example '/images/logo.png'.
description: Eugene – Portfolio pour la soutenance master IN'TECH

menu__settings:
  menu__items:
    - title: 'Accueil'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Compétences'
      submenu:
      - url: '/blog/'
        title: 'Téchniques'
      - url: '/blog/skillshumans'
        title: 'Humaines'
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/formations'
        title: 'Formations'
      - url: '/certifications'
        title: 'Certifications'
      

# Call to action button
cta__button__text: Prenez Contact

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Eugene Rodolphe MAZAMDA TANGUEU
  title: Eugene Rodolphe 
  bio: Architecte Junior Cloud & DevOps basé en France, je met en oeuvres des architecture cloud, conception des plateformes web, automatisation et industrialisation des services cloud. Quand je ne travaille pas, je suis probablement en train de cuisiner ou de voyager quelque part dans le monde. 
  image: '/images/me.jpg'
  avatar: '/images/me.jpg'
  button__text: Mes réalisations


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Dernières <span class="text-span">Réalisations</span> # Add a 'text-span' class to highlight text.
  projects__description: Je vous presente mes meilleures réalisations web , cloud et DevOps construits entièrement avec passion, simplicité et créativité !


#-------------------------------
# Testimonials Section

testimonial__title: Mon <span class="text-span">Equipe</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Alexandre CHHAN"
    image: "/images/client-2.jpg"
    designation : "Manager Squad Architecte - Tuteur"
    content : "Mettre le témoinages Alexandre ici et la photo si possible !!!."

  - name: "Karim EL KAIAL"
    image: "/images/client-1.jpg"
    designation : "Architecte Unix"
    content : "Eugène est une personne Gentil, sociable, à l'écoute, assidu. Comme points fort, il est motiver, autonome dans son travail, éfficace, polyvalent dans le domaine et surtout curieux"

  - name: "Guillaume F"
    image: "/images/client-2.jpg"
    designation : "Architecte Cloud - Azure"
    content : "J'ai eu plaisir à échanger avec Eugène durant sa présence. ll est jovial, de bonne humeur et participe grandement à la bonne ambiance au travail.Au-delà de sa personnalité, une très bonne assiduité au travail, une volonté d'aller au fond des sujets et enfin une grande capacité d'autonomie pour trouver des solutions à des problèmes complexes."

  - name: "Noël"
    image: "/images/client-3.jpg"
    designation : "Architecte Cloud - AWS "
    content : "Mettre le témoinages de Noël ici et la photo si possible !!!."

  - name: "Thomas PELTIER"
    image: "/images/client-1.jpg"
    designation : "Ingénieur Infra-IT"
    content : "Eugène est Agréable à vivre, à l'écoute de ses collègues avec beaucoup d'empathie, travailleur, motivé, déterminé et très ambitieux. Il est une personne attachant, comme amélioration à faire, il faut qu'il s'affirme un peu plus auprès des autres collaborateurs"

  - name: "Salim LE BIHAN"
    image: "/images/client-4.jpg"
    designation : "Consultant Cloud - Chef de projects"
    content : "Très bon élément, proactif et curieux, s'intégre facilement dans les équipes et apporte un véritable plus dans la cohésion, accepte et relève les challenges. Il doit détailler davantages les feedbacks. Eugène est a l'écoute, patient et prêt à aider. Bonne connaissance de Microsoft Azure. "

  - name: "Louakal FEKIH"
    image: "/images/client-4.jpg"
    designation : "Ingénieur Windows"
    content : "Eugène est une personne calme, très agréable, déterminé et avec qui c'est un plaisir de travailler. Bosseur, il n’hésitera pas a ce donner a 120% pour un projet et/ou un problème. Passionné, il intéresse a toute type d'innovation. Patience / Humilité / Respect sont 3 mots pour le qualifier."

  - name: "Elhadj Oumar DOUMBOUYA"
    image: "/images/client-4.jpg"
    designation : "Ingénieur DevOps"
    content : "Personne rigoureuse dans le travail, calme et sympathique, Forte capacité d'analyse, grande vitesse de compréhension, sérénité à toutes épreuves, Esprit d'équipe, Curiosité, Envie d'apprendre et de progresser. Avec Eugène les limites sont sans fin."

  - name: "Cheick Traore"
    image: "/images/client-4.jpg"
    designation : "Architecte Cloud"
    content : "Mettre le témoinages de Cheick et la photo si possible  ici !!!."

  - name: "Adam BAEZA"
    image: "/images/client-4.jpg"
    designation : "Ingénieur Réseaux"
    content : "Eugène est une personne agréable qui à une volonté d'apprendre. C'est une personne avec une bonne connaissance du cloud public. Comme axes d'amélioration Eugène ne se prononce pas. En deux mots C'est une personne Avenant et Sympathique"

  - name: "Gaëtan ONAHETA"
    image: "/images/client-4.jpg"
    designation : "Architecte Unix"
    content : "Eugène sait écouter et comprendre (c'est rare aujourd'hui), très agile, s'adapte et répond au besoin ou changements demandés. Très organisé dans son travail, il est transparent le long de son projet. Selon moi, son atout majeur, c'est sa capacité d'analyse, elle lui permet de voir large afin de poser les bonnes questions et de répondre de manière ciblée, efficace et pertinente avec des solutions techniques adaptées, claires et précises."

  - name: "Aure BERNIER"
    image: "/images/client-2.jpg"
    designation : "Project Manager"
    content : "Très bonne personnalité, à l'écoute et toujours enthousiaste. La motivation et l'enthousiasme sont ses points forts. Il a une compréhension des autres qui est incroyable."
#-------------------------------
# Blog Section

blog__settings:
  blog__title: Mes <span class="text-span">Compétences Techniques</span> # Add a 'text-span' class to highlight text.
  blog__description:

# Skills Human
skills__settings:
  skills__title: Mes <span class="text-span">Compétences Humaine</span>
  skills__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: mazamdatangueu@et.intechinfo.fr # Add your email for contact form
  contact__title: <span class="text-span">Prenez</span> Contact # Add a title to your form
  contact__description: Formulaire de contact. # Add a description to your form

# NOTE


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: eugenestudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/eug%C3%A8ne-rodolphe-mazamda-tangueu-82612b151/"}
- {icon: "ion-logo-github", link: "https://github.com/eugenemazamda"}
- {icon: "ion:logo-gitlab", link: "https://gitlab.com/rodolphemazamda"}
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/eugenemoussa.diop.7/"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCmERV6qF_w3QHtzhT2gx5Yg"}